type ColorType =
  | 'primary'
  | 'success'
  | 'warning'
  | 'error'
  | 'info'
  | 'secondary'
  | 'default'
type SizeType = 'xlarge' | 'large' | 'medium' | 'small' | 'tiny'
type ShapeType = 'circle' | 'square' | 'round'
type Variant =
  | 'text' // 文本按钮 特点：无背景色，文字颜色为主题色，
  | 'outlined' // 描边按钮 特点：无背景色，文字颜色为主题色， 边框颜色为主题色 实线
  | 'dashed' // 虚线按钮 特点：无背景色，文字颜色为主题色， 边框颜色为主题色 虚线
  | 'link' // 链接按钮 特点：无背景色，文字颜色为主题色， 边框颜色为透明
  | 'tonal' // 质感按钮 特点：背景色为主题色（低亮点度版），文字颜色为主题色
  | 'flat'
  | 'plain'
  | 'elevated'
  | 'filled'
  | 'soft'

//   html标签除标题和p ,code ,pre 外的字体标签
type TextVariant = 'a' | 'strong' | 'b' | 'i' | 'em' | 'u' | 's' | 'small' | 'del' | 'ins' | 'sub' | 'sup' | 'mark' | 'code' | 'pre' | 'kbd' | 'samp' | 'var' | 'cite' | 'dfn' | 'abbr' | 'time' | 'mark' | 'ruby' | 'rt' | 'rp' | 'bdi' | 'bdo' | 'span'

type TextWeightType = 'light' | 'regular' | 'medium' | 'semibold' | 'bold'
type TextLineHeightType = 'none' | 'tight' | 'snug' | 'normal' | 'relaxed' | 'loose'
interface BaseProps {
  style?: { [key: string]: string }
  class?: string
}

type PlacementType =
  | 'top'
  | 'bottom'
  | 'left'
  | 'right'
  | 'top-start'
  | 'top-end'
  | 'bottom-start'
  | 'bottom-end'
  | 'left-start'
  | 'left-end'
  | 'right-start'
  | 'right-end'

type TriggerMethodType = 'click' | 'hover' | 'focus' | 'contextmenu'

type DirectionType = 'horizontal' | 'vertical'

type JustifyType =
  | 'start'
  | 'end'
  | 'center'
  | 'between'
  | 'around'
  | 'evenly'
  | 'left'
  | 'right'

type AlignType = 'start' | 'end' | 'center' | 'baseline' | 'stretch'

type GapType = number | string | [number | string, number | string]

type ContentAlignType =
  | 'start'
  | 'end'
  | 'center'
  | 'between'
  | 'around'
  | 'stretch'

type RoundedType =
  | 'none'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | 'pill'
  | 'circle'
  | 'shaped'
  | 't'
  | 't-none'
  | 't-sm'
  | 't-lg'
  | 't-xl'
  | 't-pill'
  | 't-circle'
  | 't-shaped'
  | 'te'
  | 'te-none'
  | 'te-sm'
  | 'te-lg'
  | 'te-xl'
  | 'te-pill'
  | 'te-circle'
  | 'te-shaped'
  | 'ts'
  | 'ts-none'
  | 'ts-sm'
  | 'ts-lg'
  | 'ts-xl'
  | 'ts-pill'
  | 'ts-circle'
  | 'ts-shaped'
  | 'e'
  | 'e-none'
  | 'e-sm'
  | 'e-lg'
  | 'e-xl'
  | 'e-pill'
  | 'e-circle'
  | 'e-shaped'
  | 'b'
  | 'b-none'
  | 'b-sm'
  | 'b-lg'
  | 'b-xl'
  | 'b-pill'
  | 'b-circle'
  | 'b-shaped'
  | 'be'
  | 'be-none'
  | 'be-sm'
  | 'be-lg'
  | 'be-xl'
  | 'be-pill'
  | 'be-circle'
  | 'be-shaped'
  | 'bs'
  | 'bs-none'
  | 'bs-sm'
  | 'bs-lg'
  | 'bs-xl'
  | 'bs-pill'
  | 'bs-circle'
  | 'bs-shaped'
  | 's'
  | 's-none'
  | 's-sm'
  | 's-lg'
  | 's-xl'
  | 's-pill'
  | 's-circle'
  | 's-shaped'
